name = "grade-insight-store"
main = "cloudflare/worker.js"
compatibility_date = "2026-05-25"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "SCORE_STATE"
id = "8bea559efd4a47de9926bd221aa4f7b5"
